name: CI

on:
  push:
    tags:
      - "Versions/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            -f "Lupus/Dockerfile" \
            --tag ghcr.io/tevux-tech/lupus:${GITHUB_REF#refs/tags/Versions/} \
            --tag ghcr.io/tevux-tech/lupus:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
